[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api.example.com"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
