import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/navigation/Footer";
import { Providers } from "./GlobalReduxStore/Provider";
import ScrollToTop from "@/components/ScrollTop/ScrolltoTop";
import { HydrationOverlay } from "@builder.io/react-hydration-overlay";
import RegisterModal from "../components/Auth/RegisterModal";


export const metadata: Metadata = {
  title: "CollegeCue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-full mx-auto">
        <HydrationOverlay>
          <Providers>
            <Navbar />
            {children}
            <Footer />
            <ScrollToTop />
          </Providers>
        </HydrationOverlay>
        <RegisterModal />
      </body>
    </html>
  );
}
