const jobdata =[
    {
        heading:"Job Type",
        find:"Find Job Type",
        reviews:[
           { 
            id:1,
            Answer:"Full Time",
        },
        {
            id:2,
            Answer:"Part Time",
        },
        {
            id:3,
            Answer:"Fixed-Price",
        },
        {
            id:4,
            Answer:"Freelance",
        },
        {
            id:5,
            Answer:"Consultant",
        }
    ]
    },
    {
        heading:"Experience",
        find:"Find Experience",
        reviews:[
            {
                id:1,
            Answer:"Fresher",
        },
        {
            id:2,
            Answer:"Intermediate",
        },
        {
            id:3,
            Answer:"Mid-Senior",
        },
        {
            id:4,
            Answer:"BBA/BBM",
        },
        {
            id:5,
            Answer:"Associate",
        },
        {
            id:6,
            Answer:"Intership",
        },
        {
            id:7,
            Answer:"Expert",
        }
        ]
    },
    {
        heading:"Category",
        find:"Find Category",
        reviews:[
            {
                id:1,
                Answer:"Developer",
            },
            {
                id:2,
                Answer:"Coder",
            },
            {
                id:3,
                Answer:"Fiance",
            },
            {
                id:4,
                Answer:"Accounting",
            },
            {
                id:5,
                Answer:"Artist",
            },
            {
                id:6,
                Answer:"Marketing",
            },
            {
                id:7,
                Answer:"UI/UX",
            },
            {
                id:8,
                Answer:"Engineer",
            },
            {
                id:9,
                Answer:"Product",
            },
            {
                id:10,
                Answer:"Content Writer",
            }
        ]
    }
];
export default jobdata;